CREATE TABLE `security-db`.`users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(100) NOT NULL,
  `LAST_NAME` VARCHAR(100) NOT NULL,
  `EMAIL_ID` VARCHAR(200) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `REGISTRATION_DATE_TIME` DATETIME NOT NULL,
  `ROLE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`));

  CREATE TABLE `security-db`.`role` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`ID`));


 INSERT INTO `security-db`.`role` (`NAME`) VALUES ('STUDENT');
 INSERT INTO `security-db`.`role` (`NAME`) VALUES ('INSTRUCTOR');
